In [1]:
#import necessary libs

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
from pathlib import Path

import os

In [2]:
# Loading the dataset and making a copy of it (for safety reasons)

# Loading transformer_registry.csv

df = pd.read_csv("../data/transformer_registry.csv")

df_copy = df.copy()

In [3]:
df_copy

    transformer_id  install_year  rated_kva cooling_type    zone
0         TXR-0001          2012        250         ONAF  Zone 3
1         TXR-0002          2019        500         ONAN  Zone 3
2         TXR-0003          2009        500         OFAF  Zone 1
3         TXR-0004          2008        100         ONAF  Zone 1
4         TXR-0005          2006        250         ONAN  Zone 2
..             ...           ...        ...          ...     ...
227       TXR-0228          2015        250         ONAN  Zone 1
228       TXR-0229          2013        500         OFAF  Zone 2
229       TXR-0230          2002        100         ONAF  Zone 2
230       TXR-0231          2012        500         OFAF  Zone 3
231       TXR-0232          2010        500         ONAF  Zone 3

[232 rows x 5 columns]

In [4]:
# rows and columns ?

# df_copy.shape

print(f"rows: {df_copy.shape[0]}")
print(f"columns: {df_copy.shape[1]}")

rows: 232
columns: 5

In [5]:
# column names 

print(f"column names: {df_copy.columns.tolist()}")

column names: ['transformer_id', 'install_year', 'rated_kva', 'cooling_type', 'zone']

In [6]:
# datatypes 

df_copy.dtypes

transformer_id    object
install_year       int64
rated_kva          int64
cooling_type      object
zone              object
dtype: object

In [7]:
# first and last 10 rows 

print("First 10 rows:")
display(df_copy.head(10))

print("Last 10 rows:")
display(df_copy.tail(10))

First 10 rows:

  transformer_id  install_year  rated_kva cooling_type    zone
0       TXR-0001          2012        250         ONAF  Zone 3
1       TXR-0002          2019        500         ONAN  Zone 3
2       TXR-0003          2009        500         OFAF  Zone 1
3       TXR-0004          2008        100         ONAF  Zone 1
4       TXR-0005          2006        250         ONAN  Zone 2
5       TXR-0006          2002        250         ONAF  Zone 2
6       TXR-0007          2014        500         OFAF  Zone 2
7       TXR-0008          2015        250         ONAF  Zone 1
8       TXR-0009          2007        250         OFAF  Zone 2
9       TXR-0010          2014        100          NaN  Zone 3

Last 10 rows:

    transformer_id  install_year  rated_kva cooling_type    zone
222       TXR-0223          2001        100         OFAF  Zone 2
223       TXR-0224          2020        100         ONAF  Zone 3
224       TXR-0225          1999        100         ONAN  Zone 3
225       TXR-0226          2007        100         ONAN  Zone 3
226       TXR-0227          2014        100         ONAN  Zone 1
227       TXR-0228          2015        250         ONAN  Zone 1
228       TXR-0229          2013        500         OFAF  Zone 2
229       TXR-0230          2002        100         ONAF  Zone 2
230       TXR-0231          2012        500         OFAF  Zone 3
231       TXR-0232          2010        500         ONAF  Zone 3

In [8]:
# missing values count 

print(f"number of missing values:\n{df_copy.isna().sum()}")

number of missing values:
transformer_id    0
install_year      0
rated_kva         0
cooling_type      8
zone              0
dtype: int64

In [9]:
# duplicate rows

print(f"duplicates : {df_copy.duplicated().sum()}")

duplicates : 0

In [10]:
# statistical info

df_copy.describe()

       install_year    rated_kva
count    232.000000   232.000000
mean    2010.237069   414.224138
std        6.986059   325.523623
min     1998.000000   100.000000
25%     2005.000000   100.000000
50%     2011.000000   250.000000
75%     2016.000000   500.000000
max     2022.000000  1000.000000

In [11]:
# data info 

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transformer_id  232 non-null    object
 1   install_year    232 non-null    int64
 2   rated_kva       232 non-null    int64
 3   cooling_type    224 non-null    object
 4   zone            232 non-null    object
dtypes: int64(2), object(3)
memory usage: 9.2+ KB

In [12]:
# unique values in dataset

categorical_columns = ["cooling_type", "zone"]

for columns in categorical_columns:
    
    print(f"{columns} :")
    print(df_copy[columns].unique().tolist())

cooling_type :
['ONAF', 'ONAN', 'OFAF', nan]
zone :
['Zone 3', 'Zone 1', 'Zone 2']

In [13]:
# unique transformer_id 's

df_copy["transformer_id"].unique()

array(['TXR-0001', 'TXR-0002', 'TXR-0003', 'TXR-0004', 'TXR-0005',
       'TXR-0006', 'TXR-0007', 'TXR-0008', 'TXR-0009', 'TXR-0010',
       'TXR-0011', 'TXR-0012', 'TXR-0013', 'TXR-0014', 'TXR-0015',
       'TXR-0016', 'TXR-0017', 'TXR-0018', 'TXR-0019', 'TXR-0020',
       'TXR-0021', 'TXR-0022', 'TXR-0023', 'TXR-0024', 'TXR-0025',
       'TXR-0026', 'TXR-0027', 'TXR-0028', 'TXR-0029', 'TXR-0030',
       'TXR-0031', 'TXR-0032', 'TXR-0033', 'TXR-0034', 'TXR-0035',
       'TXR-0036', 'TXR-0037', 'TXR-0038', 'TXR-0039', 'TXR-0040',
       'TXR-0041', 'TXR-0042', 'TXR-0043', 'TXR-0044', 'TXR-0045',
       'TXR-0046', 'TXR-0047', 'TXR-0048', 'TXR-0049', 'TXR-0050',
       'TXR-0051', 'TXR-0052', 'TXR-0053', 'TXR-0054', 'TXR-0055',
       'TXR-0056', 'TXR-0057', 'TXR-0058', 'TXR-0059', 'TXR-0060',
       'TXR-0061', 'TXR-0062', 'TXR-0063', 'TXR-0064', 'TXR-0065',
       'TXR-0066', 'TXR-0067', 'TXR-0068', 'TXR-0069', 'TXR-0070',
       'TXR-0071', 'TXR-0072', 'TXR-0073', 'TXR-0074', 'TXR-0075',
       'TXR-0076', 'TXR-0077', 'TXR-0078', 'TXR-0079', 'TXR-0080',
       'TXR-0081', 'TXR-0082', 'TXR-0083', 'TXR-0084', 'TXR-0085',
       'TXR-0086', 'TXR-0087', 'TXR-0088', 'TXR-0089', 'TXR-0090',
       'TXR-0091', 'TXR-0092', 'TXR-0093', 'TXR-0094', 'TXR-0095',
       'TXR-0096', 'TXR-0097', 'TXR-0098', 'TXR-0099', 'TXR-0100',
       'TXR-0101', 'TXR-0102', 'TXR-0103', 'TXR-0104', 'TXR-0105',
       'TXR-0106', 'TXR-0107', 'TXR-0108', 'TXR-0109', 'TXR-0110',
       'TXR-0111', 'TXR-0112', 'TXR-0113', 'TXR-0114', 'TXR-0115',
       'TXR-0116', 'TXR-0117', 'TXR-0118', 'TXR-0119', 'TXR-0120',
       'TXR-0121', 'TXR-0122', 'TXR-0123', 'TXR-0124', 'TXR-0125',
       'TXR-0126', 'TXR-0127', 'TXR-0128', 'TXR-0129', 'TXR-0130',
       'TXR-0131', 'TXR-0132', 'TXR-0133', 'TXR-0134', 'TXR-0135',
       'TXR-0136', 'TXR-0137', 'TXR-0138', 'TXR-0139', 'TXR-0140',
       'TXR-0141', 'TXR-0142', 'TXR-0143', 'TXR-0144', 'TXR-0145',
       'TXR-0146', 'TXR-0147', 'TXR-0148', 'TXR-0149', 'TXR-0150',
       'TXR-0151', 'TXR-0152', 'TXR-0153', 'TXR-0154', 'TXR-0155',
       'TXR-0156', 'TXR-0157', 'TXR-0158', 'TXR-0159', 'TXR-0160',
       'TXR-0161', 'TXR-0162', 'TXR-0163', 'TXR-0164', 'TXR-0165',
       'TXR-0166', 'TXR-0167', 'TXR-0168', 'TXR-0169', 'TXR-0170',
       'TXR-0171', 'TXR-0172', 'TXR-0173', 'TXR-0174', 'TXR-0175',
       'TXR-0176', 'TXR-0177', 'TXR-0178', 'TXR-0179', 'TXR-0180',
       'TXR-0181', 'TXR-0182', 'TXR-0183', 'TXR-0184', 'TXR-0185',
       'TXR-0186', 'TXR-0187', 'TXR-0188', 'TXR-0189', 'TXR-0190',
       'TXR-0191', 'TXR-0192', 'TXR-0193', 'TXR-0194', 'TXR-0195',
       'TXR-0196', 'TXR-0197', 'TXR-0198', 'TXR-0199', 'TXR-0200',
       'TXR-0201', 'TXR-0202', 'TXR-0203', 'TXR-0204', 'TXR-0205',
       'TXR-0206', 'TXR-0207', 'TXR-0208', 'TXR-0209', 'TXR-0210',
       'TXR-0211', 'TXR-0212', 'TXR-0213', 'TXR-0214', 'TXR-0215',
       'TXR-0216', 'TXR-0217', 'TXR-0218', 'TXR-0219', 'TXR-0220',
       'TXR-0221', 'TXR-0222', 'TXR-0223', 'TXR-0224', 'TXR-0225',
       'TXR-0226', 'TXR-0227', 'TXR-0228', 'TXR-0229', 'TXR-0230',
       'TXR-0231', 'TXR-0232'], dtype=object)

In [14]:
df_copy["transformer_id"].nunique()

232

## Inspection function - for data inspection purposes.

In [15]:
import pandas as pd
import numpy as np

def inspect_csv(file_path, name=None):
    """
    Inspect a CSV dataset before data cleaning/modeling.

    Parameters:
        file_path : str
            Path to the CSV file.
        name : str, optional
            Dataset name to display.

    Returns:
        df : pandas.DataFrame
            Loaded dataset.
    """

    # Load dataset
    df = pd.read_csv(file_path)

    if name is None:
        name = os.path.basename(file_path)

    print("=" * 70)
    print(f"DATASET: {name}")
    print("=" * 70)

    # 1. Shape
    print("\n1. SHAPE")
    print("-" * 40)
    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")

    # 2. Column names
    print("\n2. COLUMNS")
    print("-" * 40)
    print(list(df.columns))

    # 3. Data types
    print("\n3. DATA TYPES")
    print("-" * 40)
    print(df.dtypes)

    # 4. Missing values
    print("\n4. MISSING VALUES")
    print("-" * 40)
    missing = df.isnull().sum()
    missing_percent = (missing / len(df)) * 100

    missing_summary = pd.DataFrame({
        "Missing_Count": missing,
        "Missing_Percentage": missing_percent.round(2)
    })

    print(missing_summary)

    # 5. Duplicate rows
    print("\n5. DUPLICATES")
    print("-" * 40)
    print(f"Duplicate rows : {df.duplicated().sum()}")

    # 6. Unique values
    print("\n6. UNIQUE VALUES")
    print("-" * 40)

    unique_summary = pd.DataFrame({
        "Unique_Count": df.nunique(),
        "Total_Rows": len(df),
    })

    print(unique_summary)

    # 7. Numerical summary
    print("\n7. NUMERICAL SUMMARY")
    print("-" * 40)
    display(df.describe())

    # 8. Categorical summary
    print("\n8. CATEGORICAL COLUMNS")
    print("-" * 40)

    categorical_columns = df.select_dtypes(
        include=["object", "category"]
    ).columns

    if len(categorical_columns) == 0:
        print("No categorical columns found.")
    else:
        for col in categorical_columns:
            print(f"\n{col}")
            print(df[col].value_counts(dropna=False))

    # 9. First few rows
    print("\n9. SAMPLE DATA")
    print("-" * 40)
    display(df.head())

    print("\n" + "=" * 70)
    print("INSPECTION COMPLETE")
    print("=" * 70)

    return df

In [16]:
# inspect & load transformer_registry.csv

registry = inspect_csv(
    "../data/transformer_registry.csv",
    "Transformer Registry"
)

======================================================================
DATASET: Transformer Registry
======================================================================

1. SHAPE
----------------------------------------
Rows    : 232
Columns : 5

2. COLUMNS
----------------------------------------
['transformer_id', 'install_year', 'rated_kva', 'cooling_type', 'zone']

3. DATA TYPES
----------------------------------------
transformer_id    object
install_year       int64
rated_kva          int64
cooling_type      object
zone              object
dtype: object

4. MISSING VALUES
----------------------------------------
                Missing_Count  Missing_Percentage
transformer_id              0                0.00
install_year                0                0.00
rated_kva                   0                0.00
cooling_type                8                3.45
zone                        0                0.00

5. DUPLICATES
----------------------------------------
Duplicate rows : 0

6. UNIQUE VALUES
----------------------------------------
                Unique_Count  Total_Rows
transformer_id           232         232
install_year              25         232
rated_kva                  4         232
cooling_type               3         232
zone                       3         232

7. NUMERICAL SUMMARY
----------------------------------------

       install_year    rated_kva
count    232.000000   232.000000
mean    2010.237069   414.224138
std        6.986059   325.523623
min     1998.000000   100.000000
25%     2005.000000   100.000000
50%     2011.000000   250.000000
75%     2016.000000   500.000000
max     2022.000000  1000.000000

8. CATEGORICAL COLUMNS
----------------------------------------

transformer_id
TXR-0001    1
TXR-0160    1
TXR-0148    1
TXR-0149    1
TXR-0150    1
           ..
TXR-0082    1
TXR-0083    1
TXR-0084    1
TXR-0085    1
TXR-0232    1
Name: transformer_id, Length: 232, dtype: int64

cooling_type
ONAF    76
OFAF    75
ONAN    73
NaN      8
Name: cooling_type, dtype: int64

zone
Zone 2    82
Zone 1    78
Zone 3    72
Name: zone, dtype: int64

9. SAMPLE DATA
----------------------------------------

  transformer_id  install_year  rated_kva cooling_type    zone
0       TXR-0001          2012        250         ONAF  Zone 3
1       TXR-0002          2019        500         ONAN  Zone 3
2       TXR-0003          2009        500         OFAF  Zone 1
3       TXR-0004          2008        100         ONAF  Zone 1
4       TXR-0005          2006        250         ONAN  Zone 2

======================================================================
INSPECTION COMPLETE
======================================================================

In [17]:
# inspect & load oil_thermal_readings.csv

oil = inspect_csv(
    "../data/oil_thermal_readings.csv",
    "Oil Thermal Readings"
)

======================================================================
DATASET: Oil Thermal Readings
======================================================================

1. SHAPE
----------------------------------------
Rows    : 1602
Columns : 5

2. COLUMNS
----------------------------------------
['record_id', 'transformer_id', 'reading_date', 'dissolved_gas_ppm', 'oil_temp_c']

3. DATA TYPES
----------------------------------------
record_id             object
transformer_id        object
reading_date          object
dissolved_gas_ppm    float64
oil_temp_c           float64
dtype: object

4. MISSING VALUES
----------------------------------------
                   Missing_Count  Missing_Percentage
record_id                      0                 0.0
transformer_id                 0                 0.0
reading_date                   0                 0.0
dissolved_gas_ppm              0                 0.0
oil_temp_c                     0                 0.0

5. DUPLICATES
----------------------------------------
Duplicate rows : 0

6. UNIQUE VALUES
----------------------------------------
                   Unique_Count  Total_Rows
record_id                  1602        1602
transformer_id              232        1602
reading_date                527        1602
dissolved_gas_ppm          1569        1602
oil_temp_c                 1602        1602

7. NUMERICAL SUMMARY
----------------------------------------

       dissolved_gas_ppm   oil_temp_c
count        1602.000000  1602.000000
mean           88.676474    54.852061
std            52.898825     8.006713
min          -146.538586    27.321725
25%            56.668197    49.340608
50%            86.305954    54.830554
75%           118.497933    60.407816
max           443.450958    82.630619

8. CATEGORICAL COLUMNS
----------------------------------------

record_id
OIL-001506    1
OIL-000895    1
OIL-001523    1
OIL-001217    1
OIL-000660    1
             ..
OIL-000680    1
OIL-001544    1
OIL-001503    1
OIL-000104    1
OIL-000622    1
Name: record_id, Length: 1602, dtype: int64

transformer_id
TXR-0126    10
TXR-0192    10
TXR-0067    10
TXR-0132    10
TXR-0058    10
            ..
TXR-0187     4
TXR-0180     4
TXR-0191     4
TXR-0207     4
TXR-0201     4
Name: transformer_id, Length: 232, dtype: int64

reading_date
2023-09-25    10
2023-03-06     9
2024-04-01     9
2023-08-02     8
2024-01-03     8
              ..
2023-03-12     1
2023-09-22     1
2023-04-05     1
2023-05-17     1
2023-02-01     1
Name: reading_date, Length: 527, dtype: int64

9. SAMPLE DATA
----------------------------------------

    record_id transformer_id reading_date  dissolved_gas_ppm  oil_temp_c
0  OIL-001506       TXR-0220   2023-08-18          34.898648   63.634816
1  OIL-000576       TXR-0084   2023-01-07          33.256817   58.186755
2  OIL-000756       TXR-0111   2023-08-25          82.053538   54.411479
3  OIL-001454       TXR-0212   2023-12-12          77.234317   53.696696
4  OIL-000490       TXR-0073   2023-01-22          99.337991   69.266781

======================================================================
INSPECTION COMPLETE
======================================================================

In [18]:
# inspect and load load_logs.csv

load = inspect_csv(
    "../data/load_logs.csv",
    "Load Logs"
)

======================================================================
DATASET: Load Logs
======================================================================

1. SHAPE
----------------------------------------
Rows    : 1978
Columns : 4

2. COLUMNS
----------------------------------------
['record_id', 'transformer_id', 'log_date', 'load_pct_of_rated']

3. DATA TYPES
----------------------------------------
record_id             object
transformer_id        object
log_date              object
load_pct_of_rated    float64
dtype: object

4. MISSING VALUES
----------------------------------------
                   Missing_Count  Missing_Percentage
record_id                      0                0.00
transformer_id                 0                0.00
log_date                       0                0.00
load_pct_of_rated             34                1.72

5. DUPLICATES
----------------------------------------
Duplicate rows : 0

6. UNIQUE VALUES
----------------------------------------
                   Unique_Count  Total_Rows
record_id                  1978        1978
transformer_id              232        1978
log_date                    530        1978
load_pct_of_rated          1944        1978

7. NUMERICAL SUMMARY
----------------------------------------

       load_pct_of_rated
count        1944.000000
mean           69.239621
std            14.829589
min            20.004487
25%            59.532609
50%            69.801028
75%            79.301486
max           112.334312

8. CATEGORICAL COLUMNS
----------------------------------------

record_id
LOA-001633    1
LOA-000177    1
LOA-000116    1
LOA-001166    1
LOA-000773    1
             ..
LOA-001039    1
LOA-000961    1
LOA-000210    1
LOA-001888    1
LOA-001276    1
Name: record_id, Length: 1978, dtype: int64

transformer_id
TXR-0172    12
TXR-0080    12
TXR-0226    12
TXR-0039    12
TXR-0202    12
            ..
TXR-0079     5
TXR-0014     5
TXR-0092     5
TXR-0204     5
TXR-0003     5
Name: transformer_id, Length: 232, dtype: int64

log_date
2023-03-06    9
2023-08-11    9
2023-10-15    9
2023-11-14    9
2023-05-18    9
             ..
2023-11-28    1
2023-05-06    1
2023-04-11    1
2023-07-16    1
2023-08-17    1
Name: log_date, Length: 530, dtype: int64

9. SAMPLE DATA
----------------------------------------

    record_id transformer_id    log_date  load_pct_of_rated
0  LOA-001633       TXR-0193  2024-01-27          78.016118
1  LOA-001418       TXR-0165  2023-02-12          80.284065
2  LOA-000816       TXR-0096  2023-10-15          73.870346
3  LOA-000437       TXR-0050  2024-02-14          53.933939
4  LOA-000537       TXR-0062  2023-04-22         109.106614

======================================================================
INSPECTION COMPLETE
======================================================================

In [19]:
# inspect and load fault_status_labeled.csv
labels = inspect_csv(
    "../data/fault_status_labeled.csv",
    "Fault Status Labeled"
)

======================================================================
DATASET: Fault Status Labeled
======================================================================

1. SHAPE
----------------------------------------
Rows    : 198
Columns : 2

2. COLUMNS
----------------------------------------
['transformer_id', 'fault_status']

3. DATA TYPES
----------------------------------------
transformer_id    object
fault_status      object
dtype: object

4. MISSING VALUES
----------------------------------------
                Missing_Count  Missing_Percentage
transformer_id              0                 0.0
fault_status                0                 0.0

5. DUPLICATES
----------------------------------------
Duplicate rows : 0

6. UNIQUE VALUES
----------------------------------------
                Unique_Count  Total_Rows
transformer_id           198         198
fault_status               2         198

7. NUMERICAL SUMMARY
----------------------------------------

       transformer_id fault_status
count             198          198
unique            198            2
top          TXR-0001       Normal
freq                1          149

8. CATEGORICAL COLUMNS
----------------------------------------

transformer_id
TXR-0001    1
TXR-0143    1
TXR-0145    1
TXR-0146    1
TXR-0147    1
           ..
TXR-0076    1
TXR-0078    1
TXR-0080    1
TXR-0081    1
TXR-0232    1
Name: transformer_id, Length: 198, dtype: int64

fault_status
Normal    149
Fault      49
Name: fault_status, dtype: int64

9. SAMPLE DATA
----------------------------------------

  transformer_id fault_status
0       TXR-0001        Fault
1       TXR-0002        Fault
2       TXR-0003        Fault
3       TXR-0004       Normal
4       TXR-0005       Normal

======================================================================
INSPECTION COMPLETE
======================================================================

In [20]:
# inspect and load fault_status_to_predict.csv
prediction = inspect_csv(
    "../data/fault_status_to_predict.csv",
    "Fault Status To Predict"
)

======================================================================
DATASET: Fault Status To Predict
======================================================================

1. SHAPE
----------------------------------------
Rows    : 34
Columns : 1

2. COLUMNS
----------------------------------------
['transformer_id']

3. DATA TYPES
----------------------------------------
transformer_id    object
dtype: object

4. MISSING VALUES
----------------------------------------
                Missing_Count  Missing_Percentage
transformer_id              0                 0.0

5. DUPLICATES
----------------------------------------
Duplicate rows : 0

6. UNIQUE VALUES
----------------------------------------
                Unique_Count  Total_Rows
transformer_id            34          34

7. NUMERICAL SUMMARY
----------------------------------------

       transformer_id
count              34
unique             34
top          TXR-0012
freq                1

8. CATEGORICAL COLUMNS
----------------------------------------

transformer_id
TXR-0012    1
TXR-0197    1
TXR-0167    1
TXR-0170    1
TXR-0172    1
TXR-0181    1
TXR-0188    1
TXR-0195    1
TXR-0198    1
TXR-0022    1
TXR-0199    1
TXR-0203    1
TXR-0207    1
TXR-0210    1
TXR-0224    1
TXR-0227    1
TXR-0166    1
TXR-0141    1
TXR-0137    1
TXR-0131    1
TXR-0126    1
TXR-0113    1
TXR-0108    1
TXR-0103    1
TXR-0089    1
TXR-0088    1
TXR-0079    1
TXR-0077    1
TXR-0074    1
TXR-0058    1
TXR-0055    1
TXR-0050    1
TXR-0049    1
TXR-0228    1
Name: transformer_id, dtype: int64

9. SAMPLE DATA
----------------------------------------

  transformer_id
0       TXR-0012
1       TXR-0022
2       TXR-0049
3       TXR-0050
4       TXR-0055

======================================================================
INSPECTION COMPLETE
======================================================================

### understand how these five CSVs relate to each other

In [21]:
#Step 1 — Check transformer_id coverage

print("Registry IDs       :", registry["transformer_id"].nunique())
print("Oil Reading IDs    :", oil["transformer_id"].nunique())
print("Load Log IDs       :", load["transformer_id"].nunique())
print("Labeled IDs        :", labels["transformer_id"].nunique())
print("Prediction IDs     :", prediction["transformer_id"].nunique())

Registry IDs       : 232
Oil Reading IDs    : 232
Load Log IDs       : 232
Labeled IDs        : 198
Prediction IDs     : 34

In [22]:
# checking whether every ID in the other datasets actually exists in the registry:

print("Oil IDs missing from registry:",
      len(set(oil["transformer_id"]) - set(registry["transformer_id"])))

print("Load IDs missing from registry:",
      len(set(load["transformer_id"]) - set(registry["transformer_id"])))

print("Labeled IDs missing from registry:",
      len(set(labels["transformer_id"]) - set(registry["transformer_id"])))

print("Prediction IDs missing from registry:",
      len(set(prediction["transformer_id"]) - set(registry["transformer_id"])))

Oil IDs missing from registry: 0
Load IDs missing from registry: 0
Labeled IDs missing from registry: 0
Prediction IDs missing from registry: 0

In [23]:
#Step 2 — Check how many readings each transformer has

oil_counts = oil["transformer_id"].value_counts()

print("Oil readings per transformer:")
display(oil_counts.describe())

Oil readings per transformer:

count    232.000000
mean       6.905172
std        2.044858
min        4.000000
25%        5.000000
50%        7.000000
75%        9.000000
max       10.000000
Name: transformer_id, dtype: float64

In [24]:
# oil[["transformer_id"]]

In [25]:
load_counts = load["transformer_id"].value_counts()

print("Load readings per transformer:")
display(load_counts.describe())

Load readings per transformer:

count    232.000000
mean       8.525862
std        2.314873
min        5.000000
25%        6.000000
50%        9.000000
75%       11.000000
max       12.000000
Name: transformer_id, dtype: float64

In [26]:
display(oil_counts.sort_values())

TXR-0201     4
TXR-0033     4
TXR-0148     4
TXR-0216     4
TXR-0052     4
            ..
TXR-0212    10
TXR-0160    10
TXR-0026    10
TXR-0117    10
TXR-0126    10
Name: transformer_id, Length: 232, dtype: int64

In [27]:
display(load_counts.sort_values())

TXR-0003     5
TXR-0095     5
TXR-0096     5
TXR-0015     5
TXR-0192     5
            ..
TXR-0162    12
TXR-0078    12
TXR-0163    12
TXR-0130    12
TXR-0172    12
Name: transformer_id, Length: 232, dtype: int64

In [28]:
# Step 3 — Check date ranges

print("Oil reading date range:")
print("Start:", oil["reading_date"].min())
print("End  :", oil["reading_date"].max())

print("\nLoad log date range:")
print("Start:", load["log_date"].min())
print("End  :", load["log_date"].max())

Oil reading date range:
Start: 2023-01-01
End  : 2024-06-30

Load log date range:
Start: 2023-01-01
End  : 2024-06-30

In [29]:
# Step 4 — Check labeled vs prediction IDs
labeled_ids = set(labels["transformer_id"])
prediction_ids = set(prediction["transformer_id"])

print("Overlap between labeled and prediction IDs:",
      len(labeled_ids & prediction_ids))

print("Total unique IDs across both:",
      len(labeled_ids | prediction_ids))

Overlap between labeled and prediction IDs: 0
Total unique IDs across both: 232